version: "3.8"

networks:
  webapp:
    driver: overlay

services:

  nginx:
    image: nginx:1.24.0
    #image: nginx:latest
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      - net
    depends_on:
      - php
      - mysql
    restart: always

  php:
    #image: php:5.6-fpm-alpine
    hostname: php
    build: ./php
    volumes:
      - ./www:/var/www
    networks:
      - net
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./db/out:/var/lib/mysql
      - ./db/in:/docker-entrypoint-initdb.d
    networks:
      - net
    restart: always

  phpmyadmin:
    image: phpmyadmin:5.0
    hostname: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PMA_HOST}
    networks:
      - net
    depends_on:
      - mysql
    restart: always


volumes:


  webapp_db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.70,nolock,soft,rw"
      device: ":/export/webapp/db"

  webapp_nginx:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.70,nolock,soft,rw"
      device: ":/export/webapp/db"

  webapp_php:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.70,nolock,soft,rw"
      device: ":/export/webapp/php"
