- name: Webapp Deploy (For master_node_00)
  hosts:  master_node_00
  vars:
    ansible_python_interpreter: /run/current-system/sw/bin/python
  tasks:

    - name: Deploy Webapp
      ansible.builtin.command: "{{ item }}"
      loop:
        - "cp -r nginx/nginx-www /mnt/webapp/"
        - "cp -r nginx/nginx-config /mnt/webapp/"
        - "cp -r nginx/nginx-ssl /mnt/webapp/"
        - "cp -r mysql/mysql-in /mnt/webapp/"
        - "cp -r mysql/mysql-out /mnt/webapp/"
        #- "docker-compose up -d"
        #- "docker-compose build"
        #- "docker-compose push"
        - "docker stack deploy --compose-file docker-compose.yaml webapp"
      args:
        chdir: "/root/deployments/webapp"
#"chdir=/root/deployments/bind9"
